# Generated by Django 5.1.2 on 2025-01-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
